# Generated by Django 5.0.3 on 2024-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productcategory_categorytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='categoryType',
        ),
        migrations.AlterField(
            model_name='user',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
