# Generated by Django 5.0.3 on 2024-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/bg2.jpg', null=True, upload_to='profile_images'),
        ),
    ]
